openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication including registration, login, and protected routes
  version: 1.0.0

paths:
  /auth/register:
    post:
      summary: Register a new user with email and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: "securePassword123"
                first_name:
                  type: string
                  example: "John"
                last_name:
                  type: string
                  example: "Doe"
              required:
                - email
                - password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '400':
          description: Invalid input or user already exists
        '422':
          description: Validation error

  /auth/login:
    post:
      summary: Login user with email and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Invalid credentials
        '404':
          description: User not found

  /auth/google:
    get:
      summary: Initiate Google OAuth login
      tags:
        - Authentication
      responses:
        '302':
          description: Redirect to Google OAuth

  /auth/google/callback:
    get:
      summary: Google OAuth callback endpoint
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect with JWT token
        '400':
          description: Invalid OAuth callback

  /auth/github:
    get:
      summary: Initiate GitHub OAuth login
      tags:
        - Authentication
      responses:
        '302':
          description: Redirect to GitHub OAuth

  /auth/github/callback:
    get:
      summary: GitHub OAuth callback endpoint
      tags:
        - Authentication
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect with JWT token
        '400':
          description: Invalid OAuth callback

  /auth/logout:
    post:
      summary: Logout user and invalidate session
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout successful
        '401':
          description: Unauthorized

  /auth/profile:
    get:
      summary: Get current user profile
      tags:
        - Authentication
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
                  is_active:
                    type: boolean
        '401':
          description: Unauthorized

  /protected/resource:
    get:
      summary: Access protected resource
      tags:
        - Protected
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Protected resource accessed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "This is a protected resource"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT